server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BD_libreriaElSaber
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Mi configuracion de Capa de Seguridad
app:
  security:
    csrf:
      enabled: false
    user:
      memory:
        users:
          - name: admin
            password: adminPass
            roles: [ADMIN]
          - name: user
            password: userPass
            roles: [USER]